# Generated by Django 2.2.6 on 2019-10-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
