# Generated by Django 2.2.6 on 2019-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0003_auto_20191001_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_credit',
        ),
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
