# Generated by Django 2.2.6 on 2019-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0004_auto_20191001_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
