# Generated by Django 2.2.6 on 2019-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0005_auto_20191001_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
