# Generated by Django 2.2.6 on 2019-10-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0008_auto_20191002_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_credit',
        ),
    ]
