# Generated by Django 2.2.6 on 2019-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0009_remove_profile_profile_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
