# Generated by Django 2.2.6 on 2019-10-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0011_auto_20191002_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barber_services', to='barber_api.Service'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('barber', models.ManyToManyField(related_name='barber_appointments', to='barber_api.Barber')),
            ],
        ),
    ]
