# Generated by Django 2.2.6 on 2019-10-03 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0012_auto_20191003_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='appointments',
            field=models.ManyToManyField(related_name='barber_appointments', to='barber_api.Appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ManyToManyField(related_name='user_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
