# Generated by Django 2.2.6 on 2019-10-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barber_api', '0013_auto_20191003_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='barber',
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
