# Generated by Django 2.2.6 on 2019-10-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0014_auto_20191003_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='appointments',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barbers', to='barber_api.Service'),
        ),
    ]
