# Generated by Django 2.2.6 on 2019-10-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0016_auto_20191006_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='barber_api.Service'),
        ),
    ]
