# Generated by Django 2.2.6 on 2019-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0018_auto_20191007_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
