# Generated by Django 2.2.6 on 2019-10-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0019_barber_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment',
            new_name='date_and_time',
        ),
    ]
