# Generated by Django 2.2.6 on 2019-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0020_auto_20191007_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
