# Generated by Django 2.2.6 on 2019-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_api', '0022_auto_20191008_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='barber_api.Service'),
        ),
    ]
